export const MOCK_PROJECTS = [
  { id: '1', name: 'EdgeKeeper', description: 'No-code visual algorithmic trading platform. Build, backtest, and deploy trading strategies without writing code.', repo_url: 'https://github.com/DevMubzly/edgekeeper', website_url: 'https://edgekeeper.app', status: 'active', created_at: '2026-05-01T00:00:00Z' },
  { id: '2', name: 'Benchline', description: 'Personal content distribution OS. Turns your coding activity into audience growth across every platform.', repo_url: 'https://github.com/DevMubzly/benchline', website_url: '', status: 'active', created_at: '2026-05-15T00:00:00Z' },
  { id: '3', name: 'SwiftNode', description: 'Serverless edge compute platform for globally distributed applications with sub-millisecond cold starts.', repo_url: 'https://github.com/DevMubzly/swiftnode', website_url: '', status: 'draft', created_at: '2026-04-20T00:00:00Z' },
]

export const MOCK_EVENTS = [
  { id: 'e1', project_id: '1', event_type: 'release', title: 'v2.1.0 — Strategy Backtesting Engine Overhaul', description: 'Complete rewrite of the backtesting engine. 10x faster execution, tick-level precision, and real-time P&L curves per trade.', url: '', analyzed: true, created_at: '2026-05-29T14:30:00Z' },
  { id: 'e2', project_id: '1', event_type: 'pr', title: 'Add SMC node types (Order Block, FVG, Liquidity)', description: 'Implemented Smart Money Concepts node types including Order Block detection, Fair Value Gaps, and Liquidity sweeps.', url: '', analyzed: true, created_at: '2026-05-28T10:15:00Z' },
  { id: 'e3', project_id: '2', event_type: 'commit', title: 'feat: add content generation API route', description: 'Added OpenAI-powered content generation endpoint that produces platform-specific posts from GitHub commits.', url: '', analyzed: false, created_at: '2026-05-27T16:45:00Z' },
  { id: 'e4', project_id: '2', event_type: 'commit', title: 'feat: calendar view with drag scheduling', description: 'Added monthly calendar view showing scheduled content with drag-to-reschedule support.', url: '', analyzed: false, created_at: '2026-05-26T09:20:00Z' },
  { id: 'e5', project_id: '1', event_type: 'commit', title: 'fix: prevent duplicate trade entries in journal', description: 'Fixed race condition causing duplicate journal entries when webhook retries happened within same second.', url: '', analyzed: true, created_at: '2026-05-25T11:00:00Z' },
]

export const MOCK_CONTENT = [
  { id: 'c1', project_id: '1', projects: { name: 'EdgeKeeper' }, title: 'Just shipped the backtesting engine rewrite — 10x faster', body: "Spent the last 3 weeks rewriting EdgeKeeper's backtesting engine from scratch. The old one worked, but it was slow. Really slow.\n\nNow: tick-level precision, real-time P&L curves, and it runs 10x faster.\n\nThe best part? Users don't have to do anything different. Same drag-and-drop interface. Just… faster results.\n\nThis is the kind of improvement that doesn't make a splashy launch post but makes users smile every single day.", channel: 'x', status: 'published', scheduled_at: '2026-05-29T12:00:00Z', published_at: '2026-05-29T12:00:00Z', reasoning: 'This is a major performance improvement that users will feel immediately. Good engagement potential.', predicted_engagement: 'High — performance improvements resonate with developers', created_at: '2026-05-29T12:00:00Z' },
  { id: 'c2', project_id: '1', projects: { name: 'EdgeKeeper' }, title: 'The technical challenge of building a no-code trading platform', body: "Building a visual strategy builder that non-coders can use is harder than building one for developers.\n\nDevelopers are used to abstractions. They understand that \"this node transforms data\" and \"that node triggers an order.\"\n\nNon-coders need the abstraction to be invisible. They need to see \"if price goes up, buy\" without thinking about data flow.\n\nThe gap between those two mental models is where most no-code tools fail.\n\nWe spent 6 months getting this right. Here's what we learned.", channel: 'linkedin', status: 'draft', scheduled_at: null, published_at: null, reasoning: 'Thought leadership piece that positions the founder as someone who deeply understands the problem.', predicted_engagement: 'Medium-high — technical content performs well on LinkedIn', created_at: '2026-05-28T10:00:00Z' },
  { id: 'c3', project_id: '2', projects: { name: 'Benchline' }, title: 'Building Benchline: my personal content operating system', body: "I built Benchline because I kept shipping code and then… nothing. No post. No thread. No update.\n\nThe gap between \"I built something\" and \"I talked about it\" was too wide.\n\nSo I built a tool that watches my GitHub repos and generates content suggestions automatically.\n\nIt's not about automating personality. It's about removing the friction between building and sharing.\n\nDogfooding it now. Let's see if it works.", channel: 'x', status: 'scheduled', scheduled_at: '2026-06-01T09:00:00Z', published_at: null, reasoning: 'Personal journey content that other builders will relate to. Good for building an audience.', predicted_engagement: 'Medium — dev audience enjoys build-in-public content', created_at: '2026-05-27T15:00:00Z' },
  { id: 'c4', project_id: '1', projects: { name: 'EdgeKeeper' }, title: 'EdgeKeeper Update: Smart Money Concepts are here', body: "Big update: we just added SMC nodes to EdgeKeeper.\n\nOrder Blocks, Fair Value Gaps, and Liquidity sweeps — all drag-and-drop.\n\nNo coding. Just connect the nodes and backtest.\n\nThis was the most requested feature. Took 2 months to implement. The hardest part was making the detection algorithms accurate enough to be useful without generating false signals.\n\nAMA about the implementation below 👇", channel: 'reddit', status: 'draft', scheduled_at: null, published_at: null, reasoning: 'Reddit community specifically requests these features. High relevance to target audience.', predicted_engagement: 'High — SMC content performs very well in trading subreddits', created_at: '2026-05-26T08:00:00Z' },
]

export const MOCK_NOTIFICATIONS = [
  { id: 'n1', type: 'release', title: 'EdgeKeeper v2.1.0 released', body: 'Strategy backtesting engine overhaul — 10x faster', read: false, created_at: '2026-05-29T14:30:00Z' },
  { id: 'n2', type: 'published', title: 'Content published on X', body: '"Just shipped the backtesting engine rewrite" went live', read: false, created_at: '2026-05-29T12:00:00Z' },
  { id: 'n3', type: 'pr', title: 'New PR: SMC node types', body: 'Order Block, FVG, and Liquidity nodes added to EdgeKeeper', read: false, created_at: '2026-05-28T10:15:00Z' },
  { id: 'n4', type: 'scheduled', title: 'Content scheduled', body: '"Building Benchline" scheduled for June 1 on X', read: true, created_at: '2026-05-27T15:00:00Z' },
  { id: 'n5', type: 'commit', title: 'Benchline: content API route', body: 'OpenAI-powered content generation endpoint added', read: true, created_at: '2026-05-27T16:45:00Z' },
]

export const MOCK_SUGGESTIONS = [
  { id: 's1', project_id: '1', platform: 'reddit', name: 'r/algotrading', url: 'https://reddit.com/r/algotrading', reason: '2.5M members actively discussing algorithmic trading strategies. Perfect for sharing EdgeKeeper strategy builds and backtest results.', relevance_score: 95, created_at: '2026-05-20T00:00:00Z' },
  { id: 's2', project_id: '1', platform: 'discord', name: 'QuantConnect Community', url: 'https://discord.gg/quantconnect', reason: 'Active algorithmic trading Discord with 15K+ members building and deploying strategies. High relevance for no-code trading tools.', relevance_score: 88, created_at: '2026-05-20T00:00:00Z' },
  { id: 's3', project_id: '1', platform: 'reddit', name: 'r/quant', url: 'https://reddit.com/r/quant', reason: 'More technical quant finance community. Good for deeper technical content about the platform architecture.', relevance_score: 75, created_at: '2026-05-20T00:00:00Z' },
  { id: 's4', project_id: '2', platform: 'reddit', name: 'r/indiehackers', url: 'https://reddit.com/r/indiehackers', reason: 'Perfect audience for build-in-public content. Community of solo founders building and shipping.', relevance_score: 90, created_at: '2026-05-25T00:00:00Z' },
  { id: 's5', project_id: '2', platform: 'discord', name: 'Indie Hackers Discord', url: 'https://discord.gg/indiehackers', reason: 'Real-time community of indie founders. Good for getting feedback and sharing progress.', relevance_score: 85, created_at: '2026-05-25T00:00:00Z' },
]
